name: SPMB
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_typeahead: ^5.0.0
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^1.5.0

# flutter:
#   assets:
#     - assets/data/
#     - assets/images/
flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
  fonts:
    - family: Cambria
      fonts:
        - asset: assets/fonts/cambria.ttc
