name: SPMB
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  fl_chart: ^0.69.0
<<<<<<< HEAD
  path_provider: 2.1.1
=======
>>>>>>> d7b2cdc2a207af96ee846ce25a9d92179d4624c7
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_typeahead: ^5.0.0
  image_picker: ^1.1.1
  intl: ^0.19.0
<<<<<<< HEAD
  shared_preferences: ^2.5.3
=======
>>>>>>> d7b2cdc2a207af96ee846ce25a9d92179d4624c7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
